# Generated by Django 4.1.3 on 2023-03-14 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo_model',
            name='complete',
        ),
    ]
