# Generated by Django 4.1.3 on 2023-03-16 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo_app', '0002_remove_todo_model_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo_model',
            name='user',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
